-- returns the species IDs of Pokemon that can use TELEPORT as a field move.
return {
    "ABRA",
    "KADABRA",
    "ALAKAZAM",
    "MEWTWO",
    "MEW",
    "CELEBI",
    "JIRACHI",
    "DEOXYS",
    "UXIE",
    "MESPRIT",
    "AZELF",
    "DIALGA",
    "PALKIA",
    "GIRATINA",
    "CRESSELIA",
    "DARKRAI",
    "ARCEUS",
}